steps:
- name: 'gradle:5.6.2-jdk8'
  entrypoint: 'gradle'
  args: ['build', '-x', 'test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/nominatim-ac', '.']
images:
  - 'eu.gcr.io/$PROJECT_ID/nominatim-ac'
