version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    volumes:
    - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
    - "9200:9200"