version: '3'
services:
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    volumes:
    - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
    - "9200:9200"


